### ISSUE TITLE
bug in msdf.c line 910

### ISSUE THREAD

**Issue by rorschach-py** [exezin/msdf-c#1]
in msdf.c, line 910:
`edge_segment_t *parts[3] = {};`
`edge_split(&contour_data[i].edges[0], parts[0], parts[1], parts[2]);`

parts[3] are wild pointers.

fix:
`edge_segment_t parts[3] = {0};`
`edge_split(&contour_data[i].edges[0], &parts[0], &parts[1], &parts[2]);`

**Comment by solenum** [comment]
Indeed, there are a few other fixes that @mattparks appears to have implemented in a fork as well, I'll work on all of this when I next get the chance :+1: 

Feel free to create a PR in the meantime.

**Comment by solenum** [comment]
Fixed as of https://github.com/exezin/msdf-c/commit/f8b9c80b9e5e458bcf65f4d1aecfc8373748aa26
